version: "3.3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  web:
    image: 1236dheerajp/git-center-server:latest
    env_file:
      - server-variables.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    user: ${CURRENT_USER}
    volumes:
      - ${HOST_REPOS_PATH}:${CONTAINER_REPOS_PATH}
      - ${HOST_AUTHORIZED_KEYS_DIR}:${CONTAINER_AUTHORIZED_KEYS_DIR}
    depends_on:
      - mongo