FROM node:13

ARG DATABASE_URI 
ARG SERVER_HOST 
ARG SERVER_PORT 
ARG SERVER_PROTOCOL 
ARG REPOSITORIES_PATH 
ARG AUTHORIZED_KEY_FILE

ENV DATABASE_URI $DATABASE_URI
ENV SERVER_HOST $SERVER_HOST 
ENV SERVER_PORT $SERVER_PORT 
ENV SERVER_PROTOCOL $SERVER_PROTOCOL 
ENV REPOSITORIES_PATH $REPOSITORIES_PATH 
ENV AUTHORIZED_KEY_FILE $AUTHORIZED_KEY_FILE

WORKDIR /usr/src/app

COPY . .

EXPOSE 3000

RUN npm ci --only=production
RUN npm run build

CMD ["npm", "start"]