version: "3.7"
services:
  mongo:
    image: mongo
    deploy:
      replicas: 1
    ports:
      - "27017:27017"
  web:
    image: 1236dheerajp/git-center-server:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:3000"
    depends_on:
      - mongo