version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test-job:
      executor:
          name: node/default
      environment:
        REPOSITORIES_PATH: /path/to/repositories
        AUTHORIZED_KEYS_DIR: /path/to/authorized_keys_dir
        SERVER_HOST: host-from-server
      steps:
        - checkout
        - restore_cache:
            key: dependency-cache-{{ checksum "package-lock.json" }}
        - run:
            name: "Installing dependencies"
            command: npm install
        - run: 
            name: "Running Tests"
            command: npm run test
        - save_cache:
            key: dependency-cache-{{ checksum "package-lock.json" }}
            paths:
              - ./node_modules
            
  deploy-job:
      working_directory: ~/app
      executor:
          name: node/default
      steps:
        - add_ssh_keys:
            fingerprints:
              - "38:94:62:c4:7e:1a:19:e9:98:5b:fd:b1:a4:61:21:f4"
        - checkout
        - setup_remote_docker
        - run:
            name: Create env files
            command: source ~/app/bin/export_env.sh
        - run: 
            name: Copy docker-compose.yml and environment files to VM
            command: scp -o "StrictHostKeyChecking no" ~/app/docker-compose.yml ~/app/bin/deploy.sh  ~/app/.env ~/app/server-variables.env ec2-user@$SSH_HOST:~/
        - run: 
            name: Build and push image
            command: | 
              docker build -t 1236dheerajp/git-center-server:latest ~/app
              echo $DOCKER_PWD | docker login -u $DOCKER_USER --password-stdin
              docker push 1236dheerajp/git-center-server:latest
        - run: 
            name: Restart server
            command: ssh -o "StrictHostKeyChecking no" ec2-user@$SSH_HOST "source deploy.sh"
workflows:
    deployment:
      jobs:
        - test-job
        - deploy-job:
            requires: 
              - test-job